/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpp_CppPathPlanning */

#ifndef _Included_cpp_CppPathPlanning
#define _Included_cpp_CppPathPlanning
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpp_CppPathPlanning
 * Method:    MapUpdate
 * Signature: ([D[DI)I
 */
JNIEXPORT jint JNICALL Java_cpp_CppPathPlanning_MapUpdate
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     cpp_CppPathPlanning
 * Method:    CenScoutMotionPlanning
 * Signature: ([[D[[D[D[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_cpp_CppPathPlanning_CenScoutMotionPlanning
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jdoubleArray, jdoubleArray);

/*
 * Class:     cpp_CppPathPlanning
 * Method:    ScoutMotionPlanning
 * Signature: ([D[DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_cpp_CppPathPlanning_ScoutMotionPlanning
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble, jdouble);

/*
 * Class:     cpp_CppPathPlanning
 * Method:    MotionPlanning
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_cpp_CppPathPlanning_MotionPlanning
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
